# Site settings
title: Airan Liang's technical blog
header-img: "img/autumn2.jpg"
tagline: ""  
description: "Graphics Rendering Mathmatic"  
baseurl: ""
# url: "http://azeril.me"  
# url: "http://localhost:4000"

url: https://airliang.github.io/

# enforce_ssl: 

# About/contact
owner: 
  name: "Airan Liang"
  email: air_liang1212@163.com
  bio: "So much I love you"

# Data

# gavatar: 
favicon: img/favicon.ico
github_username: airliang  
LinkedIn: https://www.linkedin.com/in/liangairan/

# Build settings  

# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  

markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

gems: 
- jekyll-paginate
# - jekyll-gallery-generator 
permalink: none
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Title


# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "airliang"
      header-img: "img/fantasy.jpg" # We don't want posts without a header image, that whould mean white on white


# Comments 
comments :
  provider : disqus
  disqus :
      short_name : airliang

# Analytics and webmaster tools stuff goes here
google_analytics: UA-66863061-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
